// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectMVC.Models;

#nullable disable

namespace ProjectMVC.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240418165322_init1")]
    partial class init1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ProjectMVC.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ProjectMVC.Models.ApplyForJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("ApplyForJobs");
                });

            modelBuilder.Entity("ProjectMVC.Models.Campany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("ProjectMVC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Software development related jobs",
                            Name = "Software Development"
                        },
                        new
                        {
                            Id = 2,
                            Description = "UI/UX design related jobs",
                            Name = "UI/UX Design"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Software Testing  related jobs",
                            Name = "Software Testing"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Data Science related jobs",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Digital Marketing related jobs",
                            Name = "Digital Marketing"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Graphic Design related jobs",
                            Name = "Graphic Design"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Financial Services related jobs",
                            Name = "Financial Services"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Healthcare related jobs",
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Education related jobs",
                            Name = "Education"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Sales related jobs",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Customer Support related jobs",
                            Name = "Customer Support"
                        });
                });

            modelBuilder.Entity("ProjectMVC.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ProjectMVC.Models.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("ProjectMVC.Models.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibility")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Jobs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateTime = new DateTime(2023, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Develop software applications",
                            Location = "Assiut",
                            Name = "Software Engineer",
                            Position = "Employee",
                            Qualifications = "Qualifications for a software engineer typically include ,a bachelor's degree in computer science, software engineering, or a related field. Some employers may also require a master's degree for more advanced positions. In addition to formal education, relevant skills in programming languages, software development, problem-solving, and teamwork are essential. Many software engineers also benefit from industry certifications and continuous learning to stay updated with the latest technologies and best practices.",
                            Responsibility = "The responsibilities of a software engineer often include, designing, developing, and testing software solutions, as well as collaborating with cross-functional teams to understand requirements and deliver high-quality products. Software engineers are also responsible for maintaining and enhancing existing software, debugging and troubleshooting issues, and staying updated with industry best practices and technological advancements. Additionally, they may be involved in documenting software specifications, providing technical support, and participating in code reviews to ensure quality and efficiency.",
                            Salary = 50000.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            DateTime = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Develop software solutions",
                            Location = "Cario",
                            Name = "Software Developer",
                            Position = "Developer",
                            Qualifications = "Qualifications for a software developer typically include a bachelor's degree in computer science, software engineering, or a related field. Strong programming skills, knowledge of software development methodologies, and the ability to work in a team environment are essential. Some employers may also prefer candidates with experience in specific programming languages and tools, as well as a strong understanding of software design principles and best practices.",
                            Responsibility = "The responsibilities of a software developer often include participating in the entire software development lifecycle, from concept and design to testing and maintenance. Software developers collaborate with stakeholders to understand requirements, write clean and efficient code, troubleshoot and debug software issues, and continuously improve software functionality. They may also be involved in documenting software specifications, conducting code reviews, and staying updated with industry trends and advancements.",
                            Salary = 9800.0,
                            Type = "Part Time"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            DateTime = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Engineer software systems",
                            Location = "SmartVillage",
                            Name = "Software Engineer",
                            Position = "Engineer",
                            Qualifications = "Bachelor's or master's degree in Computer Science, Software Engineering, or related field. Proven experience in software development methodologies and best practices. Proficient in multiple programming languages and frameworks relevant to the organization's tech stack. Strong analytical and problem-solving skills. Excellent communication and teamwork abilities.",
                            Responsibility = "Design, develop, test, and maintain software systems to meet client or stakeholder requirements. Collaborate with team members to identify system requirements and integrate software components. Write clean, scalable, and efficient code. Troubleshoot, debug, and upgrade existing systems. Document development phases and monitor systems.",
                            Salary = 12000.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            DateTime = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Work on backend systems",
                            Location = "Sohag",
                            Name = "Backend Developer",
                            Position = "Developer",
                            Qualifications = "Bachelor's degree in Computer Science or related field. Strong understanding of server-side languages such as Java, Python, Ruby, .NET, etc. Experience with database technology such as MySQL, Oracle, and MongoDB. Familiarity with cloud services and API integration. Excellent problem-solving skills and ability to think algorithmically.",
                            Responsibility = "Develop and maintain the server-side logic of web applications and databases. Ensure high performance and responsiveness to requests from the front-end. Participate in the entire application lifecycle, focusing on coding, debugging, and providing user support. Create data protection and security settings. Write technical documentation.",
                            Salary = 30000.0,
                            Type = "Part Time"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            DateTime = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Develop user interfaces",
                            Location = "Minya",
                            Name = "Frontend Developer",
                            Position = "Developer",
                            Qualifications = "Bachelor's degree in Computer Science, or similar. Proficiency with HTML, CSS, and JavaScript. Experience with front-end development frameworks (e.g., React, Angular, Vue). Understanding of web design principles and UX/UI best practices. Familiarity with version control tools like Git.",
                            Responsibility = "Develop new user-facing features and build reusable code and libraries for future use. Ensure the technical feasibility of UI/UX designs. Optimize application for maximum speed and scalability. Assure that all user input is validated before submitting to back-end services. Collaborate with other team members and stakeholders.",
                            Salary = 9800.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DateTime = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design user interfaces",
                            Location = "Assiut",
                            Name = "UI Designer",
                            Position = "Team Lead",
                            Qualifications = "Proven experience as a UI Designer or similar role. Strong portfolio of design projects. Proficiency in visual design and wire-framing tools. Knowledge of HTML/CSS; JavaScript is a plus. Problem-solving mindset and a keen eye for detail.",
                            Responsibility = "Gather and evaluate user requirements in collaboration with product managers and engineers. Design graphic user interface elements, like menus, tabs, and widgets. Develop UI mockups and prototypes that clearly illustrate how sites function and look. Adhere to style standards on fonts, colors, and images. Provide guidance and mentorship to junior team members.",
                            Salary = 98000.0,
                            Type = "Part time"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            DateTime = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design user interfaces",
                            Location = "Minyfia",
                            Name = "Graphic Designer",
                            Position = "Designer",
                            Qualifications = "Bachelor's degree in Graphic Design or related field. Proven graphic designing experience with a strong portfolio. Proficiency in Photoshop, Illustrator, InDesign, and other visual design and wire-framing tools. Exceptional creativity and innovation. Excellent time management and organizational skills.",
                            Responsibility = "Conceptualize visuals based on requirements. Prepare rough drafts and present ideas. Develop illustrations, logos, and other designs using software. Use appropriate colors and layouts for each graphic. Work with copywriters and creative director to produce the final design.",
                            Salary = 40000.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            DateTime = new DateTime(2024, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create user experiences",
                            Location = "Alexandria",
                            Name = "UX Designer",
                            Position = "Designer",
                            Qualifications = "Strong understanding of UX principles and best practices. Experience with user research, wireframes, and prototypes. Proficiency in UX design software such as Sketch, Adobe XD, or Figma. Excellent communication skills to collaborate with team members and stakeholders. Ability to solve problems creatively and effectively.",
                            Responsibility = "Conduct user research and testing. Develop wireframes and task flows based on user needs. Collaborate with designers and developers to create intuitive, user-friendly software. Communicate design ideas and prototypes to developers. Keep abreast of competitor products and industry trends.",
                            Salary = 9000.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            DateTime = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Design interactive interfaces",
                            Location = "Cairo",
                            Name = "Interaction Designer",
                            Position = "Designer",
                            Qualifications = "Bachelor's degree in Design, Computer Science, or relevant field. Proven experience as an Interaction Designer or similar role. Strong portfolio of design projects. Proficient in design software and interactive design tools. Excellent communication skills to collaborate with various stakeholders.",
                            Responsibility = "Develop interactive design elements and architecture for digital platforms. Create user-focused concepts and interactive solutions. Work closely with UI designers and developers to implement interactive designs. Test and refine designs based on user feedback and data. Stay updated with the latest trends in interaction design and technology.",
                            Salary = 9800.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            DateTime = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Focus on visual aspects of design",
                            Location = "Elgharbia",
                            Name = "Visual Designer",
                            Position = "Designer",
                            Qualifications = "Proven experience as a Visual Designer, Graphic Designer, or similar role. Strong portfolio of visual design projects. Proficiency in graphic design software including Adobe Photoshop, Adobe Illustrator, and other visual design tools. Excellent visual design skills with sensitivity to user-system interaction. Ability to present and defend designs and key deliverables to peers and executive level stakeholders.",
                            Responsibility = "Develop visual elements for websites, applications, and other digital platforms. Create images, icons, and layouts according to design guidelines. Work with the design team to define and implement innovative solutions for the product direction, visuals, and experience. Execute all visual design stages from concept to final hand-off to engineering. Conceptualize original ideas that bring simplicity and user friendliness to complex design roadblocks.",
                            Salary = 9800.0,
                            Type = "Part Time"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            DateTime = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Test software applications",
                            Location = "Cario",
                            Name = "QA Tester",
                            Position = "Tester",
                            Qualifications = "Qualifications for a QA Tester include a bachelor's degree in computer science, information technology, or a related field. Proficiency in various testing methodologies and tools, attention to detail, and strong analytical skills are essential. Experience with automated testing tools and a basic understanding of programming languages are advantageous.",
                            Responsibility = "Responsibilities of a QA Tester involve designing, developing, and executing test cases to ensure the quality of software applications. They detect bugs and issues, provide detailed bug reports, and collaborate with the development team to resolve issues. QA Testers also participate in the development process to understand requirements and ensure compliance with quality standards.",
                            Salary = 9400.0,
                            Type = "Part Time"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            DateTime = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automate testing processes",
                            Location = "Cario",
                            Name = "Automation Tester",
                            Position = "Tester",
                            Qualifications = "Qualifications for an Automation Tester include a bachelor’s degree in computer science, engineering, or related field. Strong programming skills and experience with automation tools like Selenium or QTP are required. Understanding of software development methodologies and experience with CI/CD tools are beneficial.",
                            Responsibility = "Responsibilities include designing and implementing automated testing frameworks, writing and executing test scripts, identifying and logging defects, and working with the development team to resolve them. Automation Testers also maintain and enhance test automation environments and integrate automation tests with the CI/CD pipeline.",
                            Salary = 9800.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Test software performance",
                            Location = "Assiut",
                            Name = "Performance Tester",
                            Position = "Tester",
                            Qualifications = "Qualifications include a bachelor's degree in computer science or a related field, with a strong understanding of performance testing methodologies and tools (e.g., LoadRunner, JMeter). Knowledge of programming and scripting languages, and experience with system monitoring tools are important.",
                            Responsibility = "Responsibilities involve planning, designing, and implementing performance tests to ensure software applications meet performance criteria. This includes analyzing test results, identifying bottlenecks, and working closely with developers to optimize performance.",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Analyze software quality",
                            Location = "Cairo",
                            Name = "Quality Analyst",
                            Position = "Analyst",
                            Qualifications = "Qualifications for a Quality Analyst include a bachelor's degree in computer science, IT, or a related field, with a deep understanding of QA methodologies. Strong analytical skills, attention to detail, and experience with QA tools and processes are essential.",
                            Responsibility = "The main responsibilities include analyzing software products to ensure they meet quality standards and user requirements. This involves developing and executing test plans, documenting defects, and collaborating with development teams to resolve issues.",
                            Salary = 29900.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Analyzing complex data sets",
                            Location = "Assiut",
                            Name = "Data Scientist",
                            Position = "Scientist",
                            Qualifications = "A Data Scientist typically holds a master’s or Ph.D. in data science, statistics, computer science, or a related field. Essential skills include proficiency in programming languages like Python or R, experience with data visualization tools, and a strong foundation in machine learning and statistical analysis.",
                            Responsibility = "Responsibilities include collecting, processing, and analyzing large data sets to identify trends and patterns. Data Scientists develop predictive models, algorithms, and conduct experiments to test their effectiveness. They also communicate findings to stakeholders and provide insights to inform decision-making.",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Implement machine learning algorithms",
                            Location = "Assiut",
                            Name = "Machine Learning Engineer",
                            Position = "Engineer",
                            Qualifications = "Qualifications include a degree in computer science, mathematics, or a related technical field. Proficiency in programming languages such as Python or Java, and experience with machine learning frameworks (e.g., TensorFlow, PyTorch) are required. A strong mathematical background is also important.",
                            Responsibility = "Machine Learning Engineers are responsible for designing and implementing machine learning models. They work on data preprocessing, model training, testing, and deployment. Collaborating with data scientists and software engineers to integrate models into production systems is also part of their role.",
                            Salary = 29200.0,
                            Type = "Part Time"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 4,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Analyze data to extract insights",
                            Location = "Assiut",
                            Name = "Data Analyst",
                            Position = "Analyst",
                            Qualifications = "A Data Analyst typically holds a bachelor's degree in information technology, computer science, or a related field. Proficiency in SQL, Excel, and data visualization tools like Tableau or Power BI is required. Analytical thinking and problem-solving skills are essential.",
                            Responsibility = "Data Analysts collect and interpret data to identify trends, patterns, and insights. They create reports and dashboards for stakeholders, helping to drive decision-making and strategic planning. Ensuring data accuracy and providing recommendations based on data analysis are key responsibilities.",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage and analyze large data sets",
                            Location = "Assiut",
                            Name = "Big Data Engineer",
                            Position = "Engineer",
                            Qualifications = "Bachelor's degree in Computer Science or related field\nExperience with big data technologies\nStrong analytical skills",
                            Responsibility = "Develop and manage big data solutions\nAnalyze data sets to identify insights\nEnsure data security and privacy",
                            Salary = 29200.0,
                            Type = "Part Time"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Plan and execute digital marketing campaigns",
                            Location = "Assiut",
                            Name = "Digital Marketing Specialist",
                            Position = "Specialist",
                            Qualifications = "Bachelor's degree in Marketing or related field\nExperience with digital marketing tools and platforms\nStrong communication and analytical skills",
                            Responsibility = "Plan and execute digital marketing campaigns\nMonitor and analyze campaign performance\nCollaborate with other teams to integrate marketing strategies",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Optimize websites for search engines",
                            Location = "Assiut",
                            Name = "SEO Analyst",
                            Position = "Analyst",
                            Qualifications = "Proven experience as SEO Analyst\nKnowledge of SEO practices and analytics tools\nExcellent communication skills",
                            Responsibility = "Perform ongoing keyword research\nOptimize website content for search engines\nTrack and analyze website analytics",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 5,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage social media presence",
                            Location = "Assiut",
                            Name = "Social Media Manager",
                            Position = "Manager",
                            Qualifications = "Experience with social media management\nStrong communication and creative skills\nAbility to analyze performance metrics",
                            Responsibility = "Develop and implement social media strategy\nCreate and distribute engaging content\nMonitor and report on performance metrics",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create engaging content for marketing purposes",
                            Location = "Assiut",
                            Name = "Content Marketing Specialist",
                            Position = "Specialist",
                            Qualifications = "Proven content creation experience\nExcellent writing and editing skills\nUnderstanding of marketing strategies",
                            Responsibility = "Develop content strategy aligned with marketing targets\nCreate and publish engaging content\nAnalyze content performance and adjust strategies as needed",
                            Salary = 29200.0,
                            Type = "Part Time"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create visual concepts",
                            Location = "Assiut",
                            Name = "Graphic Designer",
                            Position = "Designer",
                            Qualifications = "Bachelor's degree in Graphic Design or related field\nProficiency in graphic design software\nCreative thinking and attention to detail",
                            Responsibility = "Create visual aspects of marketing materials, websites, and other media\nWork with clients or the art director to determine the scope of a project\nUse digital illustration, photo editing software, and layout software to create designs",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 6,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create illustrations and graphics",
                            Location = "Assiut",
                            Name = "Illustrator",
                            Position = "Illustrator",
                            Qualifications = "Strong portfolio of illustrations or other graphics\nFamiliarity with design software and technologies\nA keen eye for aesthetics and details",
                            Responsibility = "Create original pieces of artwork for digital or print\nUse various colors, graphics and effects to better visualize each concept\nParticipate in design briefs with clients, editors, or marketers to identify their needs",
                            Salary = 29200.0,
                            Type = "Part Time"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oversee visual aspects of projects",
                            Location = "Assiut",
                            Name = "Art Director",
                            Position = "Director",
                            Qualifications = "Proven experience as an Art Director\nStrong portfolio showcasing high-end digital design skills\nAbility to think creatively and provide marketable solutions",
                            Responsibility = "Determine the best way to represent a concept visually\nDecide which photographs, art, or other design elements to use\nDevelop the overall look or style of a publication, an advertising campaign, or a theater, television, or film set",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create animated graphics and visual effects",
                            Location = "Assiut",
                            Name = "Motion Graphics Designer",
                            Position = "Designer",
                            Qualifications = "Demonstrable graphic design skills with a strong portfolio\nProficiency with required desktop publishing tools, including Photoshop, After Effects, and Adobe Animate\nA strong eye for visual composition",
                            Responsibility = "Design and create enticing motion graphics for video deliverables (corporate videos, websites, marketing demos, etc.)\nPrepare design plan, concept, and layout for motion graphic project\nAssist in selecting audio, video, colors, animation, etc. for graphic design",
                            Salary = 29200.0,
                            Type = "Part Time"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 7,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Analyze financial data and trends",
                            Location = "Assiut",
                            Name = "Financial Analyst",
                            Position = "Analyst",
                            Qualifications = "Bachelor's degree in Finance, Accounting, or related field\nExperience with financial modeling and statistical analysis\nStrong analytical and data gathering skills",
                            Responsibility = "Analyze financial data to identify trends and make recommendations\nPrepare financial reports and forecasts\nEvaluate investment opportunities and provide recommendations",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 7,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage investment portfolios",
                            Location = "Assiut",
                            Name = "Investment Banker",
                            Position = "Banker",
                            Qualifications = "Bachelor's degree in Finance, Economics, or related field\nStrong analytical and quantitative skills\nExcellent communication and interpersonal skills",
                            Responsibility = "Advise clients on investment opportunities and strategies\nManage and structure financial deals\nConduct financial analysis and market research",
                            Salary = 29200.0,
                            Type = "Part Time"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 7,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Provide financial advice to clients",
                            Location = "Assiut",
                            Name = "Financial Advisor",
                            Position = "Advisor",
                            Qualifications = "Bachelor's degree in Finance, Economics, or a related field\nCertification as a Certified Financial Planner (CFP) preferred\nStrong understanding of the financial market and investment strategies",
                            Responsibility = "Assess clients' financial situations and understand their needs\nProvide personalized financial advice and investment solutions\nMonitor and review clients' accounts and adjust plans as necessary",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 7,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage financial records and statements",
                            Location = "Assiut",
                            Name = "Accountant",
                            Position = "Accountant",
                            Qualifications = "Bachelor's degree in Accounting or related field\nCertification (e.g., CPA) is a plus\nProven experience as an accountant",
                            Responsibility = "Prepare accurate financial statements and reports\nEnsure compliance with financial laws and regulations\nManage all accounting transactions and audit financial transactions and documents",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 8,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Provide patient care",
                            Location = "Assiut",
                            Name = "Registered Nurse",
                            Position = "Nurse",
                            Qualifications = "Bachelor of Science in Nursing (BSN) degree\nActive Registered Nurse license\nProven experience as a registered nurse",
                            Responsibility = "Provide direct patient care and assess their conditions\nAdminister medications and treatments\nEducate patients and their families on health plans and preventive care",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 8,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Diagnose and treat medical conditions",
                            Location = "Assiut",
                            Name = "Medical Doctor",
                            Position = "Doctor",
                            Qualifications = "Medical degree from a recognized university\nValid license to practice the profession\nProven experience as a Medical Doctor",
                            Responsibility = "Diagnose patient conditions using examinations and tests\nPrescribe and administer treatment\nAdvise patients on health and preventive care",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 8,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Assist healthcare professionals",
                            Location = "Assiut",
                            Name = "Medical Assistant",
                            Position = "Assistant",
                            Qualifications = "Proven experience as a medical assistant or in a similar role\nKnowledge of healthcare operations and medical terminology\nStrong organizational and communication skills",
                            Responsibility = "Assist in examining and treating patients under the direction of a physician\nPrepare patients for examinations and perform routine diagnostic checks\nManage medical supplies and keep detailed records of all patient interactions",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 8,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dispense medications and provide information",
                            Location = "Assiut",
                            Name = "Pharmacist",
                            Position = "Pharmacist",
                            Qualifications = "Degree in Pharmacy or Pharmacology\nValid pharmacist license\nProven experience as a pharmacist",
                            Responsibility = "Dispense medications accurately and ensure safety and quality standards are met\nProvide information to patients about medications and their use\nManage inventory and perform administrative tasks",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 9,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Educate students in a specific subject area",
                            Location = "Assiut",
                            Name = "Teacher",
                            Position = "Teacher",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 9,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oversee school operations and staff",
                            Location = "Assiut",
                            Name = "Principal",
                            Position = "Principal",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 9,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Provide academic and personal guidance to students",
                            Location = "Assiut",
                            Name = "Guidance Counselor",
                            Position = "Counselor",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 9,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage library resources and assist patrons",
                            Location = "Assiut",
                            Name = "Librarian",
                            Position = "Librarian",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 10,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sell products or services to customers",
                            Location = "Assiut",
                            Name = "Sales Representative",
                            Position = "Representative",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 10,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Oversee sales team and strategies",
                            Location = "Assiut",
                            Name = "Sales Manager",
                            Position = "Manager",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 10,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage client accounts and relationships",
                            Location = "Assiut",
                            Name = "Account Executive",
                            Position = "Executive",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 10,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Identify and develop business opportunities",
                            Location = "Assiut",
                            Name = "Business Development Representative",
                            Position = "Representative",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 11,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Assist customers with product inquiries and issues",
                            Location = "Assiut",
                            Name = "Customer Support Specialist",
                            Position = "Specialist",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 11,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Provide technical assistance to customers",
                            Location = "Assiut",
                            Name = "Technical Support Engineer",
                            Position = "Engineer",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 11,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Handle customer inquiries and complaints",
                            Location = "Assiut",
                            Name = "Customer Service Representative",
                            Position = "Representative",
                            Salary = 29200.0,
                            Type = "Full Time"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 11,
                            DateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Manage customer support team and operations",
                            Location = "Luxor",
                            Name = "Support Manager",
                            Position = "Manager",
                            Salary = 29200.0,
                            Type = "Full Time"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ProjectMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ProjectMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ProjectMVC.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectMVC.Models.ApplyForJob", b =>
                {
                    b.HasOne("ProjectMVC.Models.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMVC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectMVC.Models.Feedback", b =>
                {
                    b.HasOne("ProjectMVC.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectMVC.Models.Job", b =>
                {
                    b.HasOne("ProjectMVC.Models.Category", "Category")
                        .WithMany("Jobs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectMVC.Models.Campany", "Company")
                        .WithMany("Jobs")
                        .HasForeignKey("CompanyId");

                    b.Navigation("Category");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("ProjectMVC.Models.Campany", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("ProjectMVC.Models.Category", b =>
                {
                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
